### ISSUE TITLE
Compile Testing Results

### ISSUE THREAD

**Issue by williamh890** [williamh890/checkers-ai#11]
Get testing results compiled into a comprehensive form. I'm not sure what the requirements for assignment 2 are, but it would be nice to have graphs of all this stuff.

**Comment by williamh890** [comment]
## Here's what I got

### Default run
- Total board evaluations = 0.00139758 seconds
- Boards calculated = 10000
- Boards evaluations per second = 715.522


### pragma omp parallel for schedule(dynamic) reduction(+:totalNodeValue)
- Total board evaluations = 0.00601939 seconds
- Boards calculated = 10000
- Boards evaluations per second = 166.13
- normalized = .232


### 1 loop unroll
- Total board evaluations = 0.0013483 seconds
- Boards calculated = 10000
- Boards evaluations per second = 741.672
- normalized = 1.036


### with floats
- Total board evaluations = 0.000715845 seconds
- Boards calculated = 10000
- Boards evaluations per second = 1396.95
- normalized = 1.95

*Normalized value are (that tests boards per sec / default boards per second)

**Comment by williamh890** [comment]
Looks to me like we definitely want to use floats.

**Comment by DuaneShaffer** [comment]
That’s awesome! Good thinking to check for floats. I forgot to do a network layout of 6 layers or more so that should be done. Were all of these results with the blondie size or 10k+? We should also try a rediculously fat network to see if it can actually use threads effectively.

**Comment by DuaneShaffer** [comment]
And the omp parallel for should be up on the loop calling the calculate node function. It doesn’t need a reduction.

**Comment by DuaneShaffer** [comment]
The following is the code I used. The only thing added is the #pragma omp parallel for. For me it goes from 1383 boards per second to 2694 boards per second. By the way, nice speed up by using a temp variable in the calculate node function, Will!

Edit: After some experimentation of additional settings I changed the # statement.


// Run the board through the network. I would use range based for loop but the first vector in _layers has been filled
	for (unsigned int x = 1; x < _layers.size(); ++x) {
		if (DEBUG)
			cout << "---------------------Calculating layer: " << x << "--------------------" << endl;
        # pragma omp parallel for schedule(guided, 2)
		for (unsigned int y = 0; y < _layers[x].size(); ++y) {
			if(DEBUG)
				cout << "Node: " << y << " _________ ";
			calculateNode(x, y);

            if (!testing) {
                _layers[x][y] = activationFunction(_layers[x][y]);
            }
		}
	}

**Comment by williamh890** [comment]
Ya, I was just focusing on the calculate node function so that's what the reduction was for.

**Comment by williamh890** [comment]
Its just not a big enough loop.

**Comment by williamh890** [comment]
@DuaneShaffer I knew pragma omp would be useful somewhere!
