### ISSUE TITLE
Project 2 - Add a minimax search with a simple piece count evaluation function

### ISSUE THREAD

**Issue by DuaneShaffer** [williamh890/checkers-ai#6]
Add an option to your gameplay from Part 1 to execute a minimax search instead of picking a random move.  This will improve the computer’s play and be a simple search function you will extend & optimize later.  Your interface should be similar to MiniMax(Board, Player, depth) which can be easily extended to implement the Iterative Deepening Search later by repeatedly calling this with increasing depth.

**Comment by DuaneShaffer** [comment]
This has two parts:
1. Make an evaluator function that takes a board and returns a piece count ( I assume something like our # pieces - their # pieces)
2. Create a move search tree function that creates all possible boards from an input board, searching to a certain depth. It evaluates every board using the piece count evaluator (from the perspective of input player) and, using minimax, returns a move to make for that player.

**Comment by williamh890** [comment]
So this has nothing to do with the neural network yet?

**Comment by DuaneShaffer** [comment]
Okay so the title of this bullet point given by genetti is the title of the issue. It’s the only place he mentions piece count evaluator. I don’t know why we would bother other than we can play against the piece count evaluator and see improvement right now instead of waiting on network to evolve.

**Comment by DuaneShaffer** [comment]
So.. seemingly nothing to do with network yet.

**Comment by williamh890** [comment]
Okay, that's not so bad then. I was looking at some pseudocode and the algo doesn't look too crazy.

**Comment by DuaneShaffer** [comment]
For the minimax + search tree?

**Comment by williamh890** [comment]
Ya, https://en.m.wikipedia.org/wiki/Minimax

**Comment by williamh890** [comment]
It looks like minimax is the search tree.
